### PR TITLE
Installable

### PR DESCRIPTION
**Pull request by gungwald**
If you wouldn't mind, I'd like to get your thoughts on this branch. I implemented a simple packaging and installation system to make it easy to get a working, standardized setup. It should work on Linux, Mac, or Windows. For Mac, I tested in on a PowerBook G4 with Mac OS X 10.4.11 so it should work on your Mac also. I updated the makefiles for all platforms. I also made some improvements to the code in Main.c.

### CODE REVIEW

**Comment by lroathe** [comment]
Funny you should ask, I was already reviewing it to see what it would take to merge it in :)

**Comment by gungwald** [comment]
Awesome. I can merge it in. I just wanted to get an opinion on whether those features are needed. I think they are. But, not sure what other people think.

**Comment by lroathe** [comment]
I think it's worth merging. I did a merge with master and was able to get the make to work on my Mac, and the install option is great. I've got a few more changes ready once that is merged (the start of a test target for instance).

**Comment by gungwald** [comment]
OK. I will try to get to that tomorrow. I'm not going to get away with taking another day off tomorrow... :-)

**Comment by lroathe** [comment]
I have a merge that works, if you would like me to do a pull request. One thing to note is that the install should work with the VS and Xc integrations, which expect this:

export MERLIN_BIN=$(MERLIN_DIR)/bin/Merlin32
export MERLIN_LIB=$(MERLIN_DIR)/lib/Merlin

**Pull request merged**
